<?php
/**
 * Coditron
 *
 * @category  Coditron
 * @package   Coditron_Reward
 * @author    Coditron
 * @copyright Copyright (c) Coditron (https://coditron.com)
 */

// phpcs:disable Magento2.Files.LineLength
// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php
/**
 * @see \Coditron\Reward\Block\Tooltip
 * @var \Coditron\Reward\Block\Tooltip $block
 */
?>
<div class="message info reward <?= $block->escapeHtmlAttr($block->getWrapperClass()) ?>">
    <?php if ($block->hasRewardMessage()) : ?>
        <span><?= $block->escapeHtml(__($block->getRewardMessage(), $this->helper(\Coditron\Reward\Helper\Data::class)->formatReward($block->getRewardPoints(), $block->getRewardAmount(), null, '<strong>%s</strong>')), ['strong']) ?></span>
    <?php endif;?>
    <?php if ($block->hasPointsBalance() && !$block->hasHideBalance()) : ?>
    <span class="reward-balance">
        <?= $block->escapeHtml(__('Your balance is %1.', $this->helper(\Coditron\Reward\Helper\Data::class)->formatReward($block->getPointsBalance(), null, null, '<strong>%s</strong>')), ['strong']) ?>
    </span>
    <?php endif;?>
    <?php if (!$block->hasHideLink()) : ?>
        <span><?= $block->escapeHtml($block->renderLearnMoreLink(), ['a']) ?></span>
    <?php endif;?>
    <?php if ($block->hasQtyLimit() && $block->hasRewardQtyLimitationMessage()) : ?>
        <span class="reward-limit"><?= $block->escapeHtml(__($block->getRewardQtyLimitationMessage(), "<strong>{$block->getQtyLimit()}</strong>"), ['strong']) ?></span>
    <?php endif;?>
    <?php if ($block->hasGuestNote()) : ?>
        <span class="reward-limit"><?= $block->escapeHtml(__($block->getGuestNote())) ?></span>
    <?php endif;?>
</div>
