<?php
/**
 * Coditron
 *
 * @category  Coditron
 * @package   Coditron_Reward
 * @author    Coditron
 * @copyright Copyright (c) Coditron (https://coditron.com)
 */
?>
<?php
/**
 * @see \Coditron\Reward\Block\Customer\Reward
 * @var \Coditron\Reward\Block\Customer\Reward $block
 */
?>
<?= $block->getChildHtml('', true) ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
