<?php
/**
 * Coditron
 *
 * @category  Coditron
 * @package   Coditron_Reward
 * @author    Coditron
 * @copyright Copyright (c) Coditron (https://coditron.com)
 */
/**
 * @var \Coditron\Reward\Block\Adminhtml\Customer\Edit\Tab\Reward\Management\Balance $block
 */
?>
<div class="fieldset-wrapper">
    <div class="fieldset-wrapper-title">
        <span class="title"><?= $block->escapeHtml(__('Reward Points Balance')) ?></span>
    </div>
    <?= $block->getChildHtml('grid') ?>
</div>
